### ISSUE TITLE
MCC Interim Linux kernel 0.12 support 

### ISSUE THREAD

**Issue by nanoR4K** [FerDev438/st-flutter-project#1]
I'm unable to compile the source code on MCC Interim Linux, how install ?

![images.jpeg](https://user-images.githubusercontent.com/47195013/235833611-2a6a1bc2-8372-4b09-8d5d-5d4eaa9c20a1.jpeg)

**Comment by FerDev438** [comment]
You need to allocate the flutter .bin into the path, maybe it runs

Em qua., 3 de mai. de 2023 01:36, Lucas L. ***@***.***>
escreveu:
